[package]
name = "commit-cli-rust"
version = "1.0.0"
edition = "2021"
authors = ["Falvet Guillaume"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["cargo"] }
owo-colors = "4.0.0"

